---
# output: github_document
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms.tex
    number_sections: true
title: | 
        | Mi proyecto
        | Subtítulo
        | Subtítulo
author:
- name: Roberto Marte
  affiliation: Estudiante, Universidad Autónoma de Santo Domingo (UASD)
abstract: "Mi resumen"
keywords: "Precipitaciones, Tipo de vivienda"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: bibliography.bib
# csl: plos-one.csl
csl: apa.csl
header-includes:
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
---


# Introducción

Preguntas de investigación o tema abordado.

# Metodología

\ldots

# Resultados

\ldots

# Discusión o Conclusiones

\ldots

# Información de soporte

\ldots

# *Script* reproducible

```{r}
library(`sf`)
library(`raster`)
library(`rgdal`)
library(`tidyverse`)
library(`spdep`)
library(`lmtest`)
library(`tmap`)
library(`RColorBrewer`)
```
#rgar archivo de datos de la ONE

```{r}
vivpersgeom_sf <- read.csv('data/vivpersgeom_sf.csv', check.names = F)
columnas <- colnames(vivpersgeom_sf)
summary(vivpersgeom_sf)
```
\ldots

# Referencias
